[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_django = ["django", "rest_framework"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = "3"
overwrite_in_place = true
line_length = 99

[tool.black]
line-length = 99
target-version = ['py310']

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = false


[tool.pytest.ini_options]
addopts = "--tb=native --cov-report term --cov=django_injector --cov-branch"
