name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django djangorestframework injector pytest pytest-cov pytest-flake8
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest
    - if: ${{ matrix.python-version == 3.9 }}
      name: Type check
      run: |
        pip install mypy
        mypy django_injector/__init__.py
